---
codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
      windows:
        target: auto
        threshold: 10%
        flags: [windows]
      web:
        target: auto
        threshold: 10%
        flags: [web]

flag_management:
  individual_flags:
    - name: windows
      paths:
        - "src/"
      carryforward: true
    - name: web
      paths:
        - "src_assets/common/assets/web/"
      carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes

ignore:
  - "tests"
  - "third-party"
