if(SUNSHINE_ENABLE_PYROWAVE)
    if(NOT WIN32)
        message(FATAL_ERROR "LuminalShine PyroWave currently requires Windows")
    endif()
    find_package(Vulkan REQUIRED)
    set(PYROWAVE_VULKAN_HEADERS_DIR "${Vulkan_INCLUDE_DIR}")
    add_subdirectory("${CMAKE_SOURCE_DIR}/third-party/pyrowave")
    target_compile_definitions(pyrowave PRIVATE VMA_STATIC_VULKAN_FUNCTIONS=0)
    target_compile_definitions(pyrowave PUBLIC VK_USE_PLATFORM_WIN32_KHR NOMINMAX)
    list(APPEND SUNSHINE_EXTERNAL_LIBRARIES pyrowave)
    list(APPEND SUNSHINE_DEFINITIONS SUNSHINE_ENABLE_PYROWAVE=1)
endif()
